kind = "web"
previewPath = "/"
title = "Web Mail Client"
version = "1.0.0"
id = "artifacts/web-mail"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26158

[services.development]
run = "pnpm --filter @workspace/web-mail run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/web-mail", "run", "build" ]
publicDir = "artifacts/web-mail/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26158"
BASE_PATH = "/"
